server:
  servlet:
    context-path: /scomparsi-batch
  port: 8102

---
#configurazione ambiente locale
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:oracle:thin:@192.168.22.20:1521/orclpdbssdsvil.ced.local
    username: acnpgm01
    password: acnpgm01
    driver-class-name: oracle.jdbc.OracleDriver
    jpa:
      show-sql: true

---
#configurazione ambiente sviluppo
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:oracle:thin:@192.168.22.20:1521/orclpdbssdsvil.ced.local
    username: acnpgm01
    password: acnpgm01
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
